global:
  scrape_interval: 10s

rule_files:
  - "node_alerts.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "<ALERTMANAGER_PRIVATE_IP>:9093"

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'node_exporter_metrics'
  static_configs:
  - targets: ['<NODE_EXPORTER_PRIVATE_IP>:9100']
